In [1]:
import numpy as np
import pandas as pd

import time
import pandas as pd 
import ast

# from visualisation import generate_map

c_df = pd.read_csv('data/combined_dataframes.csv')
c_df.tail()

,latitude,longitude,bright_ti4,acq_date,instrument,confidence,bright_ti5
708003,-10.16375,142.13250,[333.5],['2019-12-13'],['VIIRS'],['n'],[295.5]
708004,-10.16375,142.14375,[340.0],['2019-12-23'],['VIIRS'],['n'],[296.6]
708005,-10.16375,142.14750,"[341.7, 309.7]",['2019-12-23'],['VIIRS'],['n'],"[296.4, 274.4]"
708006,-10.09625,142.16250,[315.5],['2019-10-08'],['VIIRS'],['n'],[290.3]
708007,-9.39875,142.64625,"[367.0, 345.1]",['2019-12-02'],['VIIRS'],"['h', 'n']","[301.8, 301.9]"

In [2]:
# Convert the contents of the pandas array from strings looking like lists to actual lists
brightness_MODIS = c_df.loc[:,'bright_ti4'].apply(ast.literal_eval)
brightness_VIIRS = c_df.loc[:,'bright_ti5'].apply(ast.literal_eval)
instrument = c_df.loc[:,'instrument'].apply(ast.literal_eval)

In [3]:
risk = np.zeros(len(c_df.latitude))
risk

array([0., 0., 0., ..., 0., 0., 0.])

In [4]:
# calculate the mean of each of the brightnesses
import statistics 
for i,list in enumerate(brightness_MODIS):
    risk[i] += statistics.mean(list)

In [5]:
for i,list in enumerate(brightness_VIIRS):
    risk[i] += statistics.mean(list)

In [6]:
# calculate the average brightness
for i,list in enumerate(risk):
    risk[i] = risk[i] / len(instrument[i]) # divide by the number of instruments i.e. mean of 1 or mean of 2
# risk = np.mean(brightness_MODIS, brightness_VIIRS) # does not work

In [7]:
#other stuff I tried
#  ast.literal_eval(c_df.bright_ti4[1])
# c_df[2:]= c_df['bright_ti4'].apply(ast.literal_eval)
# c_df['Risk']= c_df['bright_ti4'].apply(len)
# c_df['Risk']=np.average(c_df.bright_ti4[1:20]) + np.average(c_df.bright_ti5[1:20])
# c_df.head()
# np.average(c_df.bright_ti4[1:20])
# c_df.bright_ti4.aggregate(sum)
# sum(axis=1)
# c_df

In [8]:
# time = dict()
# for i in range(len(risk)):
#     if c_df.loc[i]["acq_date"] in time:
#         time[c_df.loc[i]["acq_date"]] += 1
#     else:
#         time[c_df.loc[i]["acq_date"]] = 1

In [9]:
import datetime
import time
# create function to calculate the difference between two days
def calculateDays(date1, date2):
    day1 = time.strptime(date1, "%Y-%m-%d")
    day1 = datetime.datetime(day1[0], day1[1], day1[2])
    day2 = time.strptime(date2, "%Y-%m-%d")
    day2 = datetime.datetime(day2[0], day2[1], day2[2])
    #today = datetime.datetime.today()
    interval = day1 - day2
    return interval.days

In [10]:
# create a numpy array to store the result of timeRange
timeRange = np.zeros(len(c_df.latitude))

In [11]:
timeData = c_df["acq_date"].apply(ast.literal_eval)
for i, value in enumerate(timeData):
    # if only one day, the result will be the difference between that and the date today
    if len(value) == 1:
        timeRange[i] = abs(calculateDays("2020-02-15",timeData[i][0]))
    # if more than one day, the result will be the difference between the start day and the end day
    elif len(value) > 1:
        # start day
        date1 = timeData[i][0]
        # end day
        date2 = timeData[i][-1]
        timeRange[i] = abs(calculateDays(date2,date1))

In [12]:
# divided by the time range
for i,list in enumerate(risk):
    risk[i] = risk[i] / timeRange[i]

In [13]:
risk

array([16.63513514, 14.38181818, 14.25227273, ..., 11.31666667,
        4.66      ,  8.772     ])

In [14]:
c_df['Risk'] = risk
c_df.iloc[0:50]

,latitude,longitude,bright_ti4,acq_date,instrument,confidence,bright_ti5,Risk
0,-43.11875,146.61375,[313.6],['2020-01-09'],['MODIS'],[68],[301.9],16.635135
1,-42.83375,147.20250,[328.7],['2020-01-02'],['MODIS'],[85],[304.1],14.381818
2,-42.83000,147.21750,[324.9],['2020-01-02'],['MODIS'],[75],[302.2],14.252273
3,-42.60125,147.00375,[323.5],['2020-01-02'],['MODIS'],[66],[295.9],14.077273
4,-42.59375,146.98500,[322.1],['2020-01-03'],['MODIS'],[62],[297.0],14.397674
5,-42.59375,146.99625,[336.7],['2020-01-02'],['MODIS'],[83],[302.9],14.536364
6,-42.58250,147.01875,[338.7],['2020-01-02'],['MODIS'],[80],[302.2],14.565909
7,-42.57875,147.03000,[350.5],['2020-01-02'],['MODIS'],[96],[300.3],14.790909
8,-41.74625,148.00875,[340.1],['2020-01-09'],['MODIS'],[89],[299.6],17.289189
9,-41.74625,148.02375,[319.7],['2020-01-09'],['MODIS'],[37],[297.6],16.683784
10,-41.74250,148.01250,"[319.2, 319.8]","['2020-01-06', '2020-01-13']",['MODIS'],"[98, 73]","[285.7, 298.2]",87.350000
11,-41.74250,148.02750,"[311.9, 328.3]","['2020-01-12', '2020-01-13']",['MODIS'],"[57, 82]","[291.6, 296.9]",614.350000
12,-41.73875,148.00500,[333.5],['2020-01-09'],['MODIS'],[84],[301.6],17.164865
13,-41.73875,148.01250,[321.6],['2020-01-06'],['MODIS'],[100],[285.2],15.170000
14,-41.73875,148.02000,[322.5],['2020-01-09'],['MODIS'],[47],[298.7],16.789189
15,-41.73875,148.02375,[311.6],['2020-01-12'],['MODIS'],[63],[292.2],17.758824
16,-41.73875,148.03875,"[317.3, 301.6]","['2020-01-05', '2020-01-06']",['MODIS'],"[71, 18]","[292.3, 284.1]",597.650000
17,-41.73500,147.99750,"[331.0, 316.7]",['2020-01-06'],['MODIS'],"[72, 42]","[286.4, 284.5]",15.232500
18,-41.73500,148.02000,[313.3],['2020-01-05'],['MODIS'],[61],[289.1],14.692683
19,-41.73500,148.05000,[313.0],['2020-01-05'],['MODIS'],[53],[292.4],14.765854
20,-41.73125,148.00875,[331.2],['2020-01-06'],['MODIS'],[87],[287.6],15.470000
21,-41.73125,148.01625,[350.4],['2020-01-06'],['MODIS'],[96],[291.5],16.047500
22,-41.73125,148.02375,[320.5],['2020-01-06'],['MODIS'],[38],[285.8],15.157500
23,-41.73125,148.02750,[358.0],['2020-01-05'],['MODIS'],[99],[293.3],15.885366
24,-41.73125,148.03875,[330.1],['2020-01-04'],['MODIS'],[34],[277.6],14.469048
25,-41.72750,148.00500,[375.0],['2020-01-05'],['MODIS'],[100],[291.6],16.258537
26,-41.72750,148.01250,[314.3],['2020-01-06'],['MODIS'],[31],[285.8],15.002500
27,-41.72750,148.03500,[362.8],['2020-01-03'],['MODIS'],[100],[285.0],15.065116
28,-41.72750,148.05375,"[312.6, 335.2]","['2020-01-03', '2020-01-04']",['MODIS'],"[77, 41]","[280.2, 276.0]",602.000000
29,-41.72375,147.99375,[314.2],['2020-01-06'],['MODIS'],[38],[284.3],14.962500
30,-41.72375,148.01625,[342.0],['2020-01-06'],['MODIS'],[91],[294.5],15.912500
31,-41.72375,148.02375,[371.6],['2020-01-05'],['MODIS'],[100],[299.0],16.356098
32,-41.72375,148.04625,[305.4],['2020-01-03'],['MODIS'],[27],[266.5],13.300000
33,-41.72000,148.01250,"[312.2, 324.7]",['2020-01-03'],['MODIS'],"[58, 100]","[291.5, 282.1]",14.075581
34,-41.72000,148.03125,[327.6],['2020-01-05'],['MODIS'],[83],[296.5],15.221951
35,-41.72000,148.05000,[333.7],['2020-01-04'],['MODIS'],[49],[273.1],14.447619
36,-41.71625,148.00125,[358.5],['2020-01-05'],['MODIS'],[99],[295.3],15.946341
37,-41.71625,148.00875,"[370.6, 343.8]","['2020-01-04', '2020-01-05']",['MODIS'],"[75, 93]","[280.1, 298.6]",646.550000
38,-41.71625,148.03125,[366.5],['2020-01-03'],['MODIS'],[100],[287.6],15.211628
39,-41.71625,148.04250,"[320.1, 333.5]",['2020-01-03'],['MODIS'],"[76, 37]",[288.9],14.318605
40,-41.71625,148.05000,[335.4],['2020-01-03'],['MODIS'],[100],[281.6],14.348837
41,-41.71625,148.05750,[328.9],['2020-01-03'],['MODIS'],[48],[285.9],14.297674
42,-41.71250,148.00125,[332.7],['2020-01-03'],['MODIS'],[71],[293.3],14.558140
43,-41.71250,148.02375,[360.7],['2020-01-04'],['MODIS'],[100],[282.6],15.316667
44,-41.71250,148.04625,[327.2],['2020-01-03'],['MODIS'],[83],[289.9],14.351163
45,-41.70875,147.99375,[310.6],['2020-01-03'],['MODIS'],[23],[281.9],13.779070
46,-41.70875,148.01250,"[331.1, 415.2]",['2020-01-03'],['MODIS'],[100],"[284.0, 307.9]",15.560465
47,-41.70500,147.99750,[354.7],['2020-01-03'],['MODIS'],[97],[298.5],15.190698
48,-41.70500,148.00500,[339.7],['2020-01-03'],['MODIS'],[91],[293.3],14.720930
49,-41.70500,148.00875,[349.6],['2020-01-04'],['MODIS'],[72],[278.1],14.945238